{% set name = "GooseBib" %}
{% set org = "tdegeus" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5b31b508cd178e1549c8549298e5f956a0bbc098f0c0e76ad179852e9691ee15

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - GbibCheckAuthors = {{ name }}.cli.GbibCheckAuthors:main
    - GbibCheckKeys = {{ name }}.cli.GbibCheckKeys:main
    - GbibCheckLink = {{ name }}.cli.GbibCheckLink:main
    - GbibClean = {{ name }}.bibtex:GbibClean
    - GbibList = {{ name }}.cli.GbibList:main
    - GbibParse = {{ name }}.cli.GbibParse:main
    - GbibSelect = {{ name }}.cli.GbibSelect:main
    - GbibSelectAlias = {{ name }}.cli.GbibSelectAlias:main
    - GbibShowAuthorRename = {{ name }}.bibtex:GbibShowAuthorRename

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - bibtexparser
    - click
    - docopt
    - gitpython
    - numpy
    - python >=3
    - pyyaml
    - requests

test:
  requires:
    - git
  imports:
    - {{ name }}
  commands:
    - GbibCheckAuthors --help
    - GbibCheckKeys --help
    - GbibCheckLink --help
    - GbibClean --help
    - GbibList --help
    - GbibParse --help
    - GbibSelect --help
    - GbibSelectAlias --help
    - GbibShowAuthorRename --help

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple command-line tools to clean-up BibTeX files.
  description: Simple command-line tools to clean-up BibTeX files.
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
